import Link from "next/link";

export default function HomePage() {
  return <main>
    <section className="hero"><div className="shell hero-grid"><div><div className="eyebrow">AI-assisted exception logistics</div><h1>When logistics breaks, RESCUE takes over.</h1><p className="lead">Recover failed bulky deliveries, organise large-item returns and redirect reusable company surplus through verified local providers.</p><div className="actions"><Link className="button" href="/request">Request a recovery</Link><Link className="button ghost" href="/dashboard">View operations dashboard</Link></div></div><div className="panel" aria-label="Example recovery status"><h3>Recovery #RSC-1042</h3><div className="status"><span>Failed delivery reported</span><span className="badge">Received</span></div><div className="status"><span>Vehicle and team assessed</span><span className="badge">Human review</span></div><div className="status"><span>Verified provider</span><span className="badge">Matched</span></div><div className="status"><span>Proof of delivery</span><span className="badge">Recorded</span></div></div></div></section>
    <section className="section"><div className="shell"><div className="eyebrow">Three launch workflows</div><h2>One request. The correct recovery path.</h2><div className="grid3"><article className="card"><h3>Delivery Rescue</h3><p>Replace unavailable capacity and complete failed or delayed bulky deliveries.</p></article><article className="card"><h3>Return Recovery</h3><p>Collect, document and route bulky returns to the retailer, warehouse or repair partner.</p></article><article className="card"><h3>Surplus Recovery</h3><p>Relocate, reuse, donate, repair or responsibly route usable company equipment.</p></article></div></div></section>
    <section className="section pale"><div className="shell"><div className="eyebrow">Accountable intelligence</div><h2>AI recommends. Verified people decide and execute.</h2><p className="lead">RESCUE structures item data, suggests vehicle and team requirements, ranks eligible providers and identifies circular destinations. Dispatchers approve safety, price and compliance decisions.</p></div></section>
  </main>;
}
